squbs-unicomplex/src/test/scala/org/squbs/unicomplex/UnicomplexSpec.scala, squbs-unicomplex/src/test/scala/org/squbs/unicomplex/stashcube/StashCubeSvc.scala
Always send a response from StashCubeSvc, never hold on to requests. An HTTP request is never truly asynchronous and does need a valid response for every request. Also this unwinds the timing issue to ensure every previous step has been finished before testing the next step.
=> PR for https://github.com/paypal/squbs/issues/20

README.md, docs/validation.md, squbs-pattern/build.sbt, squbs-pattern/src/main/scala/org/squbs/pattern/validation/ValidationDirectives.scala, squbs-pattern/src/test/scala/org/squbs/pattern/validation/Person.scala, squbs-pattern/src/test/scala/org/squbs/pattern/validation/ValidationDirectivesTest.scala
Adding `validate` Spray Directive for data validation.
* Validation directive uses [Magnet Pattern](http://spray.io/blog/2012-12-13-the-magnet-pattern/).
* Actual validation is done via [Accord Validation Library](http://wix.github.io/accord/) version 0.5.
=> Validation Directives for squbs #59

squbs-httpclient/src/main/scala/org/squbs/httpclient/HttpClientJMX.scala, squbs-httpclient/src/main/scala/org/squbs/httpclient/HttpClientManager.scala, squbs-httpclient/src/main/scala/org/squbs/httpclient/endpoint/HttpClientEndpoint.scala, squbs-httpclient/src/main/scala/org/squbs/httpclient/pipeline/HttpClientPipeline.scala, squbs-httpclient/src/test/scala/org/squbs/httpclient/HttpClientManagerSpec.scala, squbs-httpclient/src/test/scala/org/squbs/httpclient/HttpClientSpec.scala, squbs-httpclient/src/test/scala/org/squbs/httpclient/dummy/DummyService.scala, squbs-httpclient/src/test/scala/org/squbs/httpclient/japi/HttpClientJSpec.scala, squbs-pipeline/src/main/scala/org/squbs/pipeline/PipelineManager.scala
Renamed verifyUri to makeFullUri as it fits the intent of the function better.
=> #72: Optimized HttpClientManager Uri.Path usage

build.sbt, squbs-admin-exp/NOTICE.txt, squbs-admin-exp/build.sbt, squbs-admin-exp/findbugsExclude.xml, squbs-admin-exp/src/main/resources/META-INF/squbs-meta.conf, squbs-admin-exp/src/main/scala/org/squbs/admin/AdminSvc.scala, squbs-admin-exp/src/main/scala/org/squbs/admin/MBeanUtil.scala, squbs-admin-exp/src/test/scala/org/squbs/admin/AdminSvcTest.scala, squbs-admin-exp/src/test/scala/org/squbs/admin/MBeanUtilTest.scala, squbs-testkit/src/main/scala/org/squbs/testkit/streaming/TestRoute.scala
A copy paste of the squbs-admin project, except minor Akka-Http related changes (e.g., respondWithMediateType etc) and unit tests.  Once we fully move to Akka Http (and drop supporting Spray), we will copy this project over squbs-admin..
=> #176 squbs-admin-exp Admin Console on Akka Http

squbs-pattern/src/main/scala/org/squbs/pattern/stream/QueueConfig.scala, squbs-pattern/src/main/scala/org/squbs/pattern/util/ConfigUtil.scala, squbs-pattern/src/test/scala/org/squbs/pattern/util/ConfigUtilSpec.scala, squbs-unicomplex/src/main/scala/org/squbs/unicomplex/ConfigUtil.scala, squbs-unicomplex/src/test/scala/org/squbs/unicomplex/ConfigUtilSpec.scala, squbs-zkcluster/.gitignore
util/ConfigUtil and unicomplex/ConfigUtil enhancements
- added method `def getOption[T](path)` to `RichConfig` class
- added method `def get[T](path,  default)` to `RichConfig` class
- added method `def get[T](path)` to `RichConfig` class
- added tests for `Regex` config value
=> #221 Add generic methods to RichConfig

squbs-pipeline/src/main/scala/org/squbs/pipeline/PipelineManager.scala, squbs-pipeline/src/test/scala/org/squbs/pipeline/PipelineManagerSpec.scala
Note that processors became a TrieMap as there is potential concurrent update at startup. This map is not concurrently accessed otherwise at runtime. Ideally, the PipelineManager should be an Actor. But that would be a future step.
=> #226: Fix for PipelineManagerSpec sporadic failures. 

docs/timeoutpolicy.md
Modified timeout policy documentation to clarify that usage of timeout policy itself will not cause timeouts to occur, and timeout occurs only when the values derived from timeout policy are used for setting the timeout values.
=>  #225 Timeout policy documentation should be more elaborate

docs/pipeline.md
the right page should be org.squbs.pipeline instead of org.squbs.proxy
=> #269: Update the package name for SimpleProcessorFactory

squbs-unicomplex/src/test/scala/org/squbs/unicomplex/streaming/LocalPortListenerSpec.scala
=> #282 Update `streaming.LocalPortListenerSpec` to use `headerValueByType`

squbs-unicomplex/src/main/scala/org/squbs/unicomplex/Bootstrap.scala
Fixed exception at shutdown if the shutdown comes from internal sources. In that case, the ActorSystem would have been shut down before the shutdownhook is called. When the shutdownhook is called, it can no longer find the ActorSystem in the table. So here we check and only shut down the actor system if found. If not found, we skip - assuming it has already been shutdown.
=> #294 Fixed exception at shutdown

squbs-unicomplex/src/main/scala/org/squbs/unicomplex/Bootstrap.scala
… if the shutdown comes from internal sources. In that case, the ActorSystem would have been shut down before the shutdownhook is called. When the shutdownhook is called, it can no longer find the ActorSystem in the table. So here we check and only shut down the actor system if found. If not found, we skip - assuming it has already been shutdown.
=> #294: Fixed exception at shutdown

docs/deduplicate.md, docs/flow-timeout.md, squbs-ext/src/main/scala/org/squbs/streams/Deduplicate.scala, squbs-ext/src/main/scala/org/squbs/streams/StreamTimeout.scala, squbs-ext/src/test/scala/org/squbs/streams/DeduplicateSpec.scala, squbs-ext/src/test/scala/org/squbs/streams/TimeoutFlowSpec.scala
We should try to optimize the flow by eliminating the `async` boundary (or limit it to the `delay` branch).  We should tackle it with https://github.com/paypal/squbs/issues/354.
We should also look at `onUpstreamFinish` and `onUpstreamFailure` scenarios in more detail with https://github.com/paypal/squbs/issues/355.
Also, created a story to add a JMX bean for the `Deduplicate` registry size: https://github.com/paypal/squbs/issues/356.
Per suggestion of @akara, we should also explore a `BidiFlow` based API: https://github.com/paypal/squbs/issues/359.
=> #327 Timeout Flow and Deduplicate

docs/testing.md, squbs-testkit/src/main/scala/org/squbs/testkit/CustomTestKit.scala, squbs-testkit/src/main/scala/org/squbs/testkit/japi/CustomTestKit.scala, squbs-testkit/src/test/java/org/squbs/testkit/japi/AbstractCustomTestKitNoClassPathTest.java, squbs-testkit/src/test/scala/org/squbs/testkit/CustomTestKitSpec.scala, squbs-unicomplex/src/main/scala/org/squbs/unicomplex/UnicomplexBoot.scala
We now need to avoid resource duplication. So built dedup logic into UnicomplexBoot resource scanning.
=> #369: Made CustomTestKit scan resources in src/main/resources, too.

project/Versions.scala, squbs-httpclient/build.sbt, squbs-httpclient/src/test/java/org/squbs/httpclient/ClientFlowHttpsEndpointTest.java, squbs-httpclient/src/test/java/org/squbs/httpclient/ClientFlowHttpsEnvTest.java, squbs-httpclient/src/test/java/org/squbs/httpclient/ClientFlowHttpsTest.java, squbs-httpclient/src/test/java/org/squbs/httpclient/ClientFlowPipelineTest.java, squbs-httpclient/src/test/java/org/squbs/httpclient/ClientFlowTest.java
- Update akka-http version to latest (10.0.3)
- Update akka version to latest (2.4.16)
- Remove the hard coded port in httpclient tests
- [X ] Title includes issue id.
=> Update: #381 Rev akka/akka-http versions to latest

squbs-actorregistry/src/main/scala/org/squbs/actorregistry/japi/ActorLookup.scala, squbs-actorregistry/src/test/java/org/squbs/actorregistry/japi/ActorRegistryTest.java
Change ActorLookup japi ask to return CompletionStage instead
of Scala Future.
=> Update: #379 return CompletionStage in ActorLookup

squbs-unicomplex/src/main/scala/org/squbs/unicomplex/FlowHandler.scala, squbs-unicomplex/src/main/scala/org/squbs/unicomplex/JavaServiceDefinitions.scala, squbs-unicomplex/src/main/scala/org/squbs/unicomplex/ServiceRegistry.scala, squbs-unicomplex/src/main/scala/org/squbs/unicomplex/Unicomplex.scala
Moved RequestContext handling out of FlowHandler and into each of the FlowSupplier implementations. Provided a stable, instrumentable entry point for Routes which is RequestContextFlow.asyncCall.
=> #408 Provided stable instrumentation point for RequestContext handling

squbs-unicomplex/src/main/scala/org/squbs/unicomplex/UnicomplexBoot.scala
- Catch nonfatal throwables in Unicomplex during component/extensions
loading.
=>  #385: Catch throwables during component loads

squbs-ext/src/main/scala/org/squbs/streams/DemandSupplyMetrics.scala, squbs-ext/src/test/scala/org/squbs/streams/DemandSupplyMetricsSpec.scala
Add a linear graph stage for collecting supply/demand metrics.
=>  #464: graphstage for demand/supply metrics

squbs-unicomplex/src/test/scala/org/squbs/unicomplex/RegisterContextSpec.scala
upgrade copyright year from 2015 to 2017
Fixes: https://github.com/paypal/squbs/issues/480
=> #480: upgrade copyright year from 2015 to 2017

docs/flow-timeout.md, squbs-ext/src/main/scala/org/squbs/streams/TimeoutBidi.scala, squbs-ext/src/main/scala/org/squbs/streams/circuitbreaker/CircuitBreakerBidi.scala, squbs-ext/src/main/scala/org/squbs/streams/circuitbreaker/japi/CircuitBreakerSettings.scala, squbs-ext/src/test/java/org/squbs/streams/TimeoutBidiFlowTest.java, squbs-ext/src/test/java/org/squbs/streams/circuitbreaker/CircuitBreakerBidiFlowTest.java, squbs-ext/src/test/scala/org/squbs/streams/TimeoutBidiFlowSpec.scala, squbs-ext/src/test/scala/org/squbs/streams/circuitbreaker/CircuitBreakerBidiFlowSpec.scala, squbs-httpclient/src/main/scala/org/squbs/httpclient/ClientFlow.scala
Thank you very much for completing this PR. We really appreciate.
Some very minor things (we can fix these little things later) is in the spelling. `shorterThenTimeout` should be `shorterThanTimeout`. Ditto for `longerThenTimeout`. As I said, it communicates adequately.
(cherry picked from commit 869a461)
=> #487 Add clean up callback for TimeOutBidi (#488)

docs/flow-retry.md, docs/flow-timeout.md, mkdocs.yml, squbs-ext/build.sbt, squbs-ext/src/main/scala/org/squbs/streams/RetryBidi.scala, squbs-ext/src/main/scala/org/squbs/streams/TimeoutBidi.scala, squbs-ext/src/main/scala/org/squbs/streams/circuitbreaker/CircuitBreakerBidi.scala, squbs-ext/src/test/java/org/squbs/streams/RetryBidiTest.java, squbs-ext/src/test/scala/org/squbs/streams/RetryBidiSpec.scala
Add a retry BIDI flow to support retrying if downstream failures
Add support in retry for a failureDecider to allow clients to customize what constitues failure
Update to use inputbuffer max for upper bound on registry size
(cherry picked from commit b3bb64)
=>  #417: Add Retry Flow support

squbs-ext/src/main/scala/org/squbs/streams/RetryBidi.scala, squbs-ext/src/test/java/org/squbs/streams/RetryBidiTest.java
The failureDecider in JAPI should allow
Function<Try<T>, Boolean> (instead of Function<Try<T>, Object)
=>  #530: Fix failureDecider JAPI in Retry stage

squbs-ext/src/main/scala/org/squbs/streams/RetryBidi.scala, squbs-ext/src/test/java/org/squbs/streams/RetryBidiTest.java
The failureDecider in JAPI should allow
Function<Try<T>, Boolean> (instead of Function<Try<T>, Object)
(Cherry-picked fromt commit 71d306afd)
=>  #530: Fix failureDecider JAPI in Retry stage (#531)

docs/flow-retry.md, squbs-ext/src/main/scala/org/squbs/streams/RetryBidi.scala, squbs-ext/src/test/java/org/squbs/streams/RetryBidiTest.java, squbs-ext/src/test/scala/org/squbs/streams/RetryBidiSpec.scala
Add support for a client specified delay duration between retries in
Retry Stage.
=>  #511: Add a delay duration to retry stage

squbs-ext/src/main/scala/org/squbs/streams/RetryBidi.scala, squbs-ext/src/test/scala/org/squbs/streams/RetryBidiSpec.scala
Check if out2 is available befor push.
Log if we cant push to out2 on any succesful/exhausted element
=>  #575: Fix "cannot push port twice error"

README.md, docs/http-services.md, docs/httpclient.md, docs/index.md
We have changed the templates to giter8 from activator and squbs docs should reflect it as well.
=> #584 Getting started page should have correct description for templates

squbs-ext/src/main/scala/org/squbs/streams/circuitbreaker/japi/CircuitBreakerSettings.scala, squbs-ext/src/test/java/org/squbs/streams/circuitbreaker/CircuitBreakerBidiFlowTest.java
Change the japi CircuitBreakerSettings for failuredecider to return Java
Boolean.
Also updated JavaTestKit -> TestKit in CircuitBreakerBidiFlowTest
=>  #549: Adjust CircuitBreaker failurdecider JAPI

docs/customizing-stream-control.md, docs/perpetualstream.md, mkdocs.yml, squbs-ext/src/main/scala/org/squbs/resolver/Resolver.scala, squbs-unicomplex/src/main/scala/org/squbs/stream/AbstractPerpetualStream.scala, squbs-unicomplex/src/main/scala/org/squbs/stream/PerpetualStream.scala, squbs-unicomplex/src/test/java/org/squbs/stream/KillSwitchMatStreamJ.java, squbs-unicomplex/src/test/resources/classpaths/JavaKillSwitchMatStream/META-INF/squbs-meta.conf, squbs-unicomplex/src/test/resources/classpaths/KillSwitchMatStream/META-INF/squbs-meta.conf, squbs-unicomplex/src/test/scala/org/squbs/stream/JavaPerpetualStreamSpec.scala, squbs-unicomplex/src/test/scala/org/squbs/stream/KillSwitchMatStream.scala, squbs-unicomplex/src/test/scala/org/squbs/stream/PerpetualStreamSpec.scala
First materialized value being `KillSwitch` is auto-recognized by `shutdown`.
=> PerpetualStream auto-recognize KillSwitch as materialized value (fixes #574)

build.sbt, docs/flow-retry.md, squbs-ext/src/main/scala/org/squbs/streams/RetryBidi.scala, squbs-ext/src/test/java/org/squbs/streams/RetryBidiTest.java, squbs-ext/src/test/scala/org/squbs/streams/RetryBidiSpec.scala
Use (java) PriorityQueue internally RetryBIDI for queue'd elements
currently being retried.
Also minor cleanup of Java API and some simplification of RetryTracker.
=>  #559: refactor RetryBidi to use PriorityQueue

docs/flow-retry.md, squbs-ext/src/main/scala/org/squbs/streams/RetryBidi.scala, squbs-ext/src/test/java/org/squbs/streams/RetryBidiTest.java, squbs-ext/src/test/scala/org/squbs/streams/RetryBidiSpec.scala
**Description:**
* Fixed ordering issue for retried elements.
* Fixed not completing the stage until there is further demand from downstream.
* A retried element with a lower retry time should be able to go to the head of the retry queue
* Optimizations on method calls and map accesses.
* Stream should complete when upstream completes. Should not require a new demand from downstream to complete (the tests were requiring an extra demand from sink).
* Dropped Overflow strategy support as anything other than backpressure  does not make sense for Retry.  It is not really a buffer, any element in retryregistry is actually inflight, which we cannot drop.
**Things to do:**
* Add test case for putting an element to the head of …
=> #559 Address Retry ordering issues and refactor the logic

docs/pipeline.md, squbs-ext/src/main/scala/org/squbs/metrics/MetricsFlow.scala, squbs-httpclient/src/main/scala/org/squbs/httpclient/ClientFlow.scala, squbs-httpclient/src/test/scala/org/squbs/httpclient/ClientFlowPipelineSpec.scala, squbs-pipeline/build.sbt, squbs-pipeline/src/main/scala/org/squbs/pipeline/PipelineExtension.scala, squbs-pipeline/src/main/scala/org/squbs/pipeline/RequestContext.scala, squbs-pipeline/src/test/java/org/squbs/pipeline/AbortableBidiFlowTest.java, squbs-pipeline/src/test/java/org/squbs/pipeline/DummyFlow2J.java, squbs-pipeline/src/test/java/org/squbs/pipeline/DummyFlowJ.java, squbs-pipeline/src/test/java/org/squbs/pipeline/PipelineExtensionTest.java, squbs-pipeline/src/test/java/org/squbs/pipeline/PostFlowJ.java, squbs-pipeline/src/test/java/org/squbs/pipeline/PreFlowJ.java, squbs-pipeline/src/test/java/org/squbs/pipeline/RequestContextTest.java, squbs-pipeline/src/test/resources/testng.yaml, squbs-pipeline/src/test/scala/org/squbs/pipeline/AbortableBidiFlowSpec.scala, squbs-pipeline/src/test/scala/org/squbs/pipeline/PipelineExtensionSpec.scala, squbs-pipeline/src/test/scala/org/squbs/pipeline/RequestContextSpec.scala, squbs-unicomplex/src/main/scala/org/squbs/unicomplex/FlowHandler.scala, squbs-unicomplex/src/test/scala/org/squbs/unicomplex/pipeline/PipelineSpec.scala
Add Java friendly PipelineFlowFactory API.
Add additional javadsl HttpRequest/Response APIs into RequestContext
=>  #451: Add java friendly api for PipelineFlowFactory

.gitignore, docs/flow-retry.md, docs/httpclient.md, squbs-ext/src/main/scala/org/squbs/streams/Retry.scala, squbs-ext/src/test/java/org/squbs/streams/RetryTest.java, squbs-ext/src/test/scala/org/squbs/streams/RetryJMXSpec.scala
Expose some metrics from the Retry stage for visibility.
=>  #551: Expose metrics from Retry stage

docs/persistent-buffer.md, project/Versions.scala, squbs-pattern/src/main/scala/org/squbs/pattern/stream/PersistentQueue.scala
There was [a memory leak at Akka-HTTP 10.1.2](https://github.com/akka/akka-http/issues/2067). These two commits were from https://github.com/paypal/squbs/pull/667, I didn't push yet.
=> Bump Chronicle Queue and Akka-HTTP version

squbs-unicomplex/src/main/scala/org/squbs/stream/PerpetualStream.scala, squbs-unicomplex/src/test/scala/org/squbs/stream/PerpetualStreamMatValueSpec.scala, squbs-unicomplex/src/test/scala/org/squbs/stream/PerpetualStreamSpec.scala
that materialize to `Sink[T, NotUsed]` or to any `Product` whose first element
is a `Sink[T, NotUsed]`.
=>  #661 PerpetualStreamMatValue.matValue should support PerpetualStreams

docs/flow-retry.md, squbs-ext/src/main/scala/org/squbs/streams/Retry.scala, squbs-ext/src/test/scala/org/squbs/streams/RetrySpec.scala
#690 When RetryStage cannot find a match, log an error message and propagate the result regardless of whether or not it failed.
- [ x] Title includes issue id.
- [x ] Description of the change added.
- [ x] Tests added.
- [x ] Documentation added/updated.
=> 690 retrystage logging improvements

build.sbt, project/Versions.scala, squbs-pattern/src/test/scala/org/squbs/pattern/stream/BroadcastBufferSpec.scala, squbs-unicomplex/src/test/scala/org/squbs/unicomplex/ListenerStateSpec.scala, squbs-unicomplex/src/test/scala/org/squbs/unicomplex/MaterializerSpec.scala, squbs-zkcluster/build.sbt, version.sbt
#695: Bump dependency versions to latest versions of akka, akka-http etc.
Also minor test updates to fix issues introduced.
=> 695: Bump dependency versions to latest

.travis.yml
Adding scala version to `sbt publish` command in travis config to fix cross scala version publish
=> Fix cross scala version publish

build.sbt, docs/flow-timeout.md, docs/timeoutpolicy.md, project/Versions.scala, squbs-ext/src/main/scala/org/squbs/streams/Timeout.scala, squbs-ext/src/main/scala/org/squbs/streams/circuitbreaker/impl/AtomicCircuitBreakerState.scala, squbs-ext/src/test/java/org/squbs/streams/TimeoutTest.java, squbs-ext/src/test/java/org/squbs/streams/circuitbreaker/CircuitBreakerStateTest.java, squbs-ext/src/test/java/org/squbs/streams/circuitbreaker/CircuitBreakerTest.java, squbs-httpclient/src/test/java/org/squbs/httpclient/ClientFlowTest.java, squbs-pattern/src/main/java/org/squbs/pattern/timeoutpolicy/TimedFn.java, squbs-pattern/src/main/scala/org/squbs/pattern/timeoutpolicy/TimeoutPolicy.scala, squbs-pattern/src/test/java/org/squbs/pattern/timeoutpolicy/TimeoutPolicyJ.java, squbs-pattern/src/test/scala/org/squbs/pattern/timeoutpolicy/TimeoutPolicySpec.scala, squbs-unicomplex/src/main/scala/org/squbs/lifecycle/GracefulStopHelper.scala, squbs-unicomplex/src/test/java/org/squbs/lifecycle/GracefulStopHelperTest.java, squbs-unicomplex/src/test/java/org/squbs/stream/KillSwitchStreamJ.java, squbs-unicomplex/src/test/java/org/squbs/stream/KillSwitchWithChildActorStreamJ.java, squbs-unicomplex/src/test/java/org/squbs/stream/ProperShutdownStreamJ.java
It's still WIP, but I want to discuss some of the changes.
=> Java duration (#694)

docs/bootstrap.md
I've never heard of scanning the class loader.  I'm familiar with class path scanning.
Did a quick google search as well and nothing came up for "scanning class loader".
I'm assuming class path was meant.
=> Squbs bootstrap process scans class path or class loader?

squbs-ext/src/test/java/org/squbs/streams/TimeoutTest.java, squbs-ext/src/test/java/org/squbs/streams/circuitbreaker/CircuitBreakerTest.java, squbs-testkit/src/test/java/org/squbs/testkit/japi/InfoRouteWithActor.java
Fix #703.
Replace deprecated method - `akka.pattern.PatternsCS.ask` with `akka.pattern.Patterns.ask`
=> Replace deprecated method - akka.pattern.PatternsCS.ask (#703)

squbs-unicomplex/src/main/resources/reference.conf, squbs-unicomplex/src/main/scala/org/squbs/unicomplex/UnicomplexBoot.scala, squbs-unicomplex/src/test/resources/classpaths/UnicomplexBootTimeouts/META-INF/squbs-meta.conf, squbs-unicomplex/src/test/scala/org/squbs/unicomplex/UnicomplexBootSpec.scala, squbs-unicomplex/src/test/scala/org/squbs/unicomplex/timeout/ConfigurableInitTimeActor.scala
Tests and documentation TBD.
- [ x] Title includes issue id.
- [ x] Description of the change added.
- [ x] Also please review [CONTRIBUTING.md](https://github.com/paypal/squbs/blob/master/CONTRIBUTING.md).
=>  #711 [WIP] Make service infra startup timeout configurable

squbs-unicomplex/src/main/scala/org/squbs/unicomplex/UnicomplexBoot.scala
The fix we have on master for 711 has error messages that make it hard to triage.  This addresses that.
- [ x] Title includes issue id.
- [x ] Description of the change added.
- [ x] Commits are squashed.
=>  #711 proposal for better error messages..

squbs-pattern/src/main/scala/org/squbs/pattern/stream/PersistentQueue.scala, squbs-pattern/src/test/scala/org/squbs/pattern/stream/PersistentBufferAtLeastOnceSpec.scala
When the queue is started, it attempts to resume from the old
index. However, this operation may fail if e.g. no commits have
occurred yet.
This ensures that the first element is only dropped if resuming
from an index succeeds, and adds a test to validate this behavior.
=> PersistentBufferAtLeastOnce: Don't drop elements if no commits are made
