squbs-unicomplex/src/main/scala/org/squbs/unicomplex/Unicomplex.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/BadProxySpec.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/MultipleUnicomplexTest.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/SystemStatusTest.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/UnicomplexSpec.scala

Also changed the response type to StatusReport case class. This allows better pattern matching without lost type information.

https://github.com/paypal/squbs/issues/23: Made ReportStatus more accessible.

---

squbs-pipeline/src/main/scala/org/squbs/pipeline/RequestContext.scala

Case has been covered in https://github.com/paypal/squbs/blob/master/squbs-pipeline/src/test/scala/org/squbs/pipeline/RequestContextSpec.scala#L56

Use flapMap, not match for avoiding Some(null) case

---

squbs-actormonitor/src/main/scala/org/squbs/actormonitor/ActorMonitorBean.scala
squbs-httpclient/src/main/scala/org/squbs/httpclient/HttpClient.scala
squbs-httpclient/src/main/scala/org/squbs/httpclient/HttpClientManager.scala
squbs-httpclient/src/main/scala/org/squbs/httpclient/endpoint/impl/SimpleServiceEndpointResolver.scala
squbs-httpclient/src/main/scala/org/squbs/httpclient/json/JacksonProtocol.scala
squbs-httpclient/src/main/scala/org/squbs/httpclient/pipeline/HttpClientPipeLineActor.scala
squbs-httpclient/src/main/scala/org/squbs/httpclient/pipeline/impl/RequestHeaderHandler.scala
squbs-httpclient/src/test/scala/org/squbs/httpclient/dummy/DummyService.scala
squbs-httpclient/src/test/scala/org/squbs/httpclient/endpoint/impl/SimpleServiceEndpointResolverSpec.scala
squbs-pipeline/src/main/scala/org/squbs/pipeline/PipelineHandlerManager.scala
squbs-pipeline/src/test/scala/org/squbs/pipeline/PipelineHandlerManagerSpec.scala
squbs-pipeline/src/test/scala/org/squbs/pipeline/PipelineManagerSpec.scala
squbs-pipeline/src/test/scala/org/squbs/pipeline/SimpleProcessorSpec.scala

Commits are now squashed and ready to merge. Please review and comment.

Fixed static analysis for issue #54

---

docs/bootstrap.md
project/plugins.sbt
squbs-testkit/src/main/scala/org/squbs/testkit/SimpleTestKit.scala
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/Unicomplex.scala
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/UnicomplexBoot.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/BadUnicomplexBootSpec.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/MultiListenerSpec.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/MultipleUnicomplexTest.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/SystemStatusTest.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/Timeouts.scala

Components should be able to start and all signals are received until the start timeout.

#79 Fixed the startup policy

---

squbs-pattern/src/main/scala/org/squbs/pattern/spray/japi/ChunkedMessageEndFactory.scala
squbs-pattern/src/main/scala/org/squbs/pattern/spray/japi/HttpEntityFactory.scala
squbs-pattern/src/main/scala/org/squbs/pattern/spray/japi/MarshallerHelper.scala
squbs-pattern/src/main/scala/org/squbs/pattern/spray/japi/MessageChunkFactory.scala
squbs-pattern/src/test/java/org/squbs/pattern/spray/japi/JApiTest.java
squbs-pattern/src/test/scala/org/squbs/pattern/spray/japi/ScalaAccess.scala

https://github.com/paypal/squbs/issues/65

---

docs/testing.md

Please cherry-pick this commit to branch RELEASE-0.7.X before releasing 0.7.1.

#117: Documented the new TestRoute signature.

---

README.md
build.sbt
docs/console.md
project/plugins.sbt
squbs-admin/NOTICE.txt
squbs-admin/build.sbt
squbs-admin/findbugsExclude.xml
squbs-admin/src/main/resources/META-INF/squbs-meta.conf
squbs-admin/src/main/scala/org/squbs/admin/AdminSvc.scala
squbs-admin/src/main/scala/org/squbs/admin/MBeanUtil.scala
squbs-admin/src/test/scala/org/squbs/admin/AdminSvcTest.scala
squbs-admin/src/test/scala/org/squbs/admin/MBeanUtilTest.scala
squbs-testkit/src/test/scala/org/squbs/testkit/TestRouteTest.scala
squbs-unicomplex/src/main/resources/reference.conf

All good to merge from my side.

#31 Admin console - use json4s to render

---

squbs-pattern/src/main/scala/org/squbs/pattern/orchestration/japi/AbstractOrchestrator.scala
squbs-pattern/src/test/java/org/squbs/pattern/orchestration/japi/Messages.java
squbs-pattern/src/test/java/org/squbs/pattern/orchestration/japi/OrchestratorTest.java
squbs-pattern/src/test/java/org/squbs/pattern/orchestration/japi/ServiceEmulator.java
squbs-pattern/src/test/java/org/squbs/pattern/orchestration/japi/TestOrchestrator.java

Documentation changes to follow.

#129: Provided orchestrator functionality for Java

---

squbs-httpclient/src/main/scala/org/squbs/httpclient/HttpClient.scala
squbs-httpclient/src/test/scala/org/squbs/httpclient/HttpClientSpec.scala

and ensured code coverage on HttpClient.

#144: Restored HttpClient.withPipeline API

---

build.sbt
project/plugins.sbt
squbs-admin/NOTICE.txt
squbs-admin/build.sbt
squbs-admin/findbugsExclude.xml
squbs-admin/src/main/resources/META-INF/squbs-meta.conf
squbs-admin/src/main/scala/org/squbs/admin/AdminSvc.scala
squbs-admin/src/main/scala/org/squbs/admin/MBeanUtil.scala
squbs-admin/src/test/scala/org/squbs/admin/AdminSvcTest.scala
squbs-admin/src/test/scala/org/squbs/admin/MBeanUtilTest.scala

#31Initial addition of admin console.

---

squbs-unicomplex/src/main/scala/org/squbs/unicomplex/Unicomplex.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/CubeActorErrorStatesSpec.scala

The name is the route name with "target" added, such as "test1-myclass-routetarget" or "test1-myclass-handlertarget".

#76: Assigned name of proxied route or handler. 

---

squbs-httpclient/src/main/scala/org/squbs/httpclient/json/JacksonProtocol.scala
squbs-httpclient/src/test/java/org/squbs/httpclient/japi/PageData.java
squbs-httpclient/src/test/java/org/squbs/httpclient/japi/PagedResult.java
squbs-httpclient/src/test/scala/org/squbs/httpclient/dummy/DummyService.scala
squbs-httpclient/src/test/scala/org/squbs/httpclient/japi/HttpClientJSpec.scala

Code needing certain modules need to register themselves. Also added test cases covering the issue.

#160: Removed any Jackson module registration

---

squbs-httpclient/src/main/scala/org/squbs/httpclient/pipeline/HttpClientPipeline.scala
squbs-httpclient/src/test/scala/org/squbs/httpclient/HttpClientSpec.scala
squbs-httpclient/src/test/scala/org/squbs/httpclient/dummy/DummyService.scala
squbs-httpclient/src/test/scala/org/squbs/httpclient/japi/HttpClientJSpec.scala

And send back an exception with the response. Also added test cases for no content deserialization.

#161: Fixed deserialization to check for no content

---

docs/registry.md
squbs-actorregistry/build.sbt
squbs-actorregistry/src/main/scala/org/squbs/actorregistry/ActorLookup.scala
squbs-actorregistry/src/main/scala/org/squbs/actorregistry/ActorRegistry.scala
squbs-actorregistry/src/main/scala/org/squbs/actorregistry/ActorRegistryBean.scala
squbs-actorregistry/src/main/scala/org/squbs/actorregistry/japi/ActorLookup.scala
squbs-actorregistry/src/test/java/org/squbs/actorregistry/japi/ActorRegistryTest.java
squbs-actorregistry/src/test/scala/org/squbs/actorregistry/ActorRegistrySpec.scala
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/UnicomplexBoot.scala

Fixed a few bugs and usability issues along the way.

#180: Provided Java API for ActorLookup

---

docs/streamingpipeline.md
squbs-streamingpipeline/src/main/scala/org/squbs/pipeline/streaming/PipelineExtension.scala
squbs-streamingpipeline/src/test/scala/org/squbs/pipeline/streaming/AbortableBidiFlowSpec.scala
squbs-streamingpipeline/src/test/scala/org/squbs/pipeline/streaming/PipelineExtensionSpec.scala
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/streaming/FlowHandler.scala
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/streaming/Headers.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/streaming/pipeline/PipelineSpec.scala

* API change for PipelineFlowFactory to take ActorSystem
* Add WebContextHeader
* Minor refactoring on calling the routeActor

#176 #110 PipelineFlowFactory take actor system and refactoring

---

squbs-unicomplex/src/main/scala/org/squbs/unicomplex/JMX.scala
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/ServiceRegistry.scala
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/ServiceRegistryBase.scala
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/streaming/ServiceRegistry.scala
squbs-unicomplex/src/test/resources/classpaths/ListenerState/META-INF/squbs-meta.conf
squbs-unicomplex/src/test/resources/classpaths/streaming/ListenerState/META-INF/squbs-meta.conf
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/CubeActorErrorStatesSpec.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/ListenerStateSpec.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/streaming/CubeActorErrorStatesSpec.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/streaming/ListenerStateSpec.scala

and also fail the system state if custom SSLContext cannot be created

#183 Report listener initialization failures on JMX

---

.travis.yml
README.md
build.sbt
docs/persistent-buffer.md
jvmopts
squbs-actormonitor/build.sbt
squbs-actorregistry/build.sbt
squbs-admin-exp/build.sbt
squbs-admin/build.sbt
squbs-httpclient/build.sbt
squbs-pattern/NOTICE.txt
squbs-pattern/build.sbt
squbs-pattern/src/main/java/org/squbs/pattern/stream/IndexFile.java
squbs-pattern/src/main/scala/org/squbs/pattern/stream/PersistentBuffer.scala
squbs-pattern/src/main/scala/org/squbs/pattern/stream/PersistentQueue.scala
squbs-pattern/src/test/scala/org/squbs/pattern/stream/PersistentBufferSpec.scala
squbs-pattern/src/test/scala/org/squbs/pattern/stream/PersistentQueueSpec.scala
squbs-pipeline/build.sbt
squbs-streamingpipeline/build.sbt
squbs-testkit/build.sbt
squbs-unicomplex/build.sbt
squbs-zkcluster/build.sbt

Making PR for review. Please do not yet merge util the docs are provided.

#207: PersistentBuffer feature for Akka Streams

---

docs/persistent-buffer.md
squbs-pattern/build.sbt
squbs-pattern/src/main/scala/org/squbs/pattern/stream/PersistentBuffer.scala
squbs-pattern/src/main/scala/org/squbs/pattern/stream/PersistentQueue.scala
squbs-pattern/src/main/scala/org/squbs/pattern/stream/QueueSerializer.scala
squbs-pattern/src/test/scala/org/squbs/pattern/stream/PersistentBufferSpec.scala
squbs-pattern/src/test/scala/org/squbs/pattern/stream/PersistentQueueSpec.scala
squbs-testkit/src/main/resources/default-test.conf

Generified `PersistentBuffer` to support `Any` time.

#211: Make PersistentBuffer support generic types.

---

squbs-pattern/src/test/scala/org/squbs/pattern/validation/ValidationDirectivesTest.scala
squbs-unicomplex/build.sbt
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/streaming/ValidationDirectives.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/streaming/ValidationDirectivesSpec.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/streaming/validation/Person.scala

- added unicomplex/streaming/ValidationDirectives based on wix/accord library
- added dependency on akka-http-testkit
- added tests for ValidationDirectives

#200 Validation Directives on Akka Http

---

squbs-actorregistry/src/main/scala/org/squbs/actorregistry/ActorRegistryInit.scala
squbs-admin-exp/src/main/scala/org/squbs/admin/AdminSvc.scala
squbs-admin/src/main/scala/org/squbs/admin/AdminSvc.scala
squbs-pattern/src/main/scala/org/squbs/pattern/util/ConfigUtil.scala
squbs-pattern/src/test/scala/org/squbs/pattern/util/ConfigUtilSpec.scala
squbs-unicomplex/src/main/scala/org/squbs/dispatcher/ForkJoinConfigurator.scala
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/Bootstrap.scala
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/ConfigUtil.scala
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/JMX.scala
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/ServiceRegistryBase.scala
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/Unicomplex.scala
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/UnicomplexBoot.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/ConfigUtilSpec.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/UnicomplexBootSpec.scala

- added Duration typetag to unicomplex/ConfigUtil and pattern/ConfigUtil
- added FiniteDuration typetag to unicomplex/ConfigUtil and pattern/ConfigUtil
- added tests
- refactored config calls

#140 ConfigUtil.getOptionalDuration changes time unit

---

docs/bootstrap.md
docs/lifecycle.md
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/Bootstrap.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/ShutdownSpec.scala

#202 Register JVM shutdown hook and add configuration for delayed shutdown

---

squbs-unicomplex/src/main/scala/org/squbs/unicomplex/Bootstrap.scala

#202 Delete unnecessary config retrieval from `Shutdown`

---

docs/httpclient.md

Documentation updated

---

docs/bootstrap.md

#254 Doc fix for ExtensionLifecycle

---

squbs-pattern/src/main/scala/org/squbs/pattern/stream/BroadcastBuffer.scala
squbs-pattern/src/main/scala/org/squbs/pattern/stream/PersistentBuffer.scala
squbs-pattern/src/main/scala/org/squbs/pattern/stream/PersistentQueue.scala
squbs-pattern/src/main/scala/org/squbs/pattern/stream/PersistentQueueCloserActor.scala
squbs-pattern/src/test/scala/org/squbs/pattern/stream/BroadcastBufferSpec.scala
squbs-pattern/src/test/scala/org/squbs/pattern/stream/PersistentBufferSpec.scala
squbs-pattern/src/test/scala/org/squbs/pattern/stream/PersistentQueueSpec.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/streaming/LocalPortListenerSpec.scala

#260 Remove synchronous close in PersistentQueue

---

docs/persistent-buffer.md
squbs-pattern/src/main/scala/org/squbs/pattern/stream/PersistentQueue.scala
squbs-pattern/src/main/scala/org/squbs/pattern/stream/QueueConfig.scala
squbs-pattern/src/test/scala/org/squbs/pattern/stream/BroadcastBufferCommitOrderSpec.scala
squbs-pattern/src/test/scala/org/squbs/pattern/stream/PersistentBufferCommitOrderSpec.scala
squbs-pattern/src/test/scala/org/squbs/pattern/stream/PersistentBufferSpec.scala
squbs-pattern/src/test/scala/org/squbs/pattern/stream/QueueConfigSpec.scala
squbs-pattern/src/test/scala/org/squbs/pattern/stream/StreamSpecUtil.scala

#242 PersistentBuffer & BroadcastBuffer commit safety

---

docs/streams-lifecycle.md
project/Versions.scala
samples/bottles/bottlecube/build.sbt
samples/bottles/bottlesvc/build.sbt
samples/pubsub/pubsubsvc/build.sbt

#274 Akka 2.4.11

---

project/build.properties
samples/bottles/project/build.properties
samples/pubsub/project/build.properties

#276 sbt 0.13.12

---

.travis.yml
samples/bottles/build.sbt
samples/pubsub/build.sbt

#262 scala 2.11.8

---

samples/bottles/bottlecube/build.sbt
samples/bottles/bottlesvc/build.sbt
samples/bottles/build.sbt
samples/pubsub/build.sbt
samples/pubsub/pubsubsvc/build.sbt
version.sbt

Update version to 0.9.0-SNAPSHOT

---

docs/pipeline.md

#269 Documentation bug in pipeline.md

---

docs/persistent-buffer.md
squbs-pattern/src/main/scala/org/squbs/pattern/stream/BroadcastBuffer.scala
squbs-pattern/src/main/scala/org/squbs/pattern/stream/BroadcastBufferBase.scala
squbs-pattern/src/main/scala/org/squbs/pattern/stream/PersistentBuffer.scala
squbs-pattern/src/main/scala/org/squbs/pattern/stream/PersistentBufferBase.scala
squbs-pattern/src/main/scala/org/squbs/pattern/stream/PersistentQueue.scala
squbs-pattern/src/main/scala/org/squbs/pattern/stream/QueueConfig.scala
squbs-pattern/src/test/scala/org/squbs/pattern/stream/BroadcastBufferAtLeastOnceSpec.scala
squbs-pattern/src/test/scala/org/squbs/pattern/stream/BroadcastBufferCommitOrderSpec.scala
squbs-pattern/src/test/scala/org/squbs/pattern/stream/PersistentBufferAtLeastOnceSpec.scala
squbs-pattern/src/test/scala/org/squbs/pattern/stream/PersistentBufferCommitOrderSpec.scala
squbs-pattern/src/test/scala/org/squbs/pattern/stream/QueueConfigSpec.scala
squbs-pattern/src/test/scala/org/squbs/pattern/stream/StreamSpecUtil.scala
squbs-pattern/src/test/scala/org/squbs/pattern/timeoutpolicy/TimeoutPolicyFeatureSpec.scala

This introduces an API change that's why it goes to 0.9.0.. To use `commit` for at least once semantics, one should prefer `PersistentBufferAtLeastOnce` and `BroadcastBufferAtLeastOnce`, these two will output `Event`.  `PersistentBuffer` and `BroadcastBuffer` will keep the input type.

#243 BroadcastBuffer does not need `event` type for auto commit enabled

---

project/build.properties
project/plugins.sbt

#305: Upgraded codacy plugin 

---

project/build.properties
project/plugins.sbt

#305: Upgraded codacy plugin and sbt.

---

project/build.properties
project/plugins.sbt

#305 for 0.8.X downgrade to latest stable Codacy plugin 1.3.4 according to Codacy

---

squbs-unicomplex/src/main/scala/org/squbs/unicomplex/ServiceRegistry.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/MultiListenerSpec.scala

The portBindings call will only return ports successfully bound. Errors will be left out.

#302: Fixed match error on ServerBindingInfo when dealing with bind error cases

---

docs/bootstrap.md
squbs-actorregistry/src/test/resources/classpaths/TestCubeWithRouter/META-INF/squbs-meta.conf
squbs-actorregistry/src/test/scala/org/squbs/actorregistry/ActorRegistrySpec.scala
squbs-actorregistry/src/test/scala/org/squbs/actorregistry/testcube/TestCube.scala

#291: Replicated whole test suites to work with actors behind routers.

---

squbs-admin/build.sbt

#309: Changed squbs-admin-exp project name inside build.sbt to squbs-admin

---

squbs-unicomplex/src/main/scala/org/squbs/unicomplex/Unicomplex.scala
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/UnicomplexBoot.scala
squbs-unicomplex/src/test/resources/classpaths/ClassNotFoundCube/META-INF/squbs-meta.conf
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/ClassNotFoundSpec.scala

#331: Ensure a ClassNotFoundException of actors or services results in a system startup failure.

---

samples/bottles/bottlecube/build.sbt
samples/bottles/bottlesvc/build.sbt

Fix #357: added missing refrence to scalatestV

---

squbs-ext/build.sbt
squbs-ext/src/main/scala/org/squbs/endpoint/Endpoint.scala
squbs-ext/src/main/scala/org/squbs/env/Environment.scala
squbs-ext/src/test/java/org/squbs/endpoint/DummyLocalhostJavaResolver.java
squbs-ext/src/test/java/org/squbs/endpoint/EndpointTest.java
squbs-ext/src/test/java/org/squbs/env/EnvironmentTest.java
squbs-ext/src/test/scala/org/squbs/endpoint/EndpointSpec.scala
squbs-ext/src/test/scala/org/squbs/endpoint/EndpointTestHelper.scala
squbs-ext/src/test/scala/org/squbs/env/DummyEnvironmentResolver.scala
squbs-ext/src/test/scala/org/squbs/env/EnvTestHelper.scala
squbs-ext/src/test/scala/org/squbs/env/EnvironmentSpec.scala
squbs-ext/src/test/scala/org/squbs/metrics/MetricsFlowSpec.scala

#362: Brought up code coverage for Java APIs and more

---

squbs-pattern/src/main/scala/org/squbs/pattern/stream/PersistentQueue.scala

replace map with foreach

---

squbs-httpclient/build.sbt

#381 Fix akka-testkit in build.sbt

---

docs/httpclient.md
squbs-httpclient/src/main/scala/org/squbs/httpclient/ClientFlow.scala
squbs-httpclient/src/main/scala/org/squbs/httpclient/DefaultHttpEndpointResolver.scala
squbs-httpclient/src/test/scala/org/squbs/httpclient/ClientConfigurationSpec.scala
squbs-httpclient/src/test/scala/org/squbs/httpclient/ClientFlowSpec.scala
squbs-httpclient/src/test/scala/org/squbs/httpclient/DefaultHttpEndpointResolverSpec.scala
squbs-httpclient/src/test/scala/org/squbs/httpclient/HttpClientJMXSpec.scala

#342 Default HttpEndpointResolver

---

squbs-unicomplex/src/main/scala/org/squbs/unicomplex/UnicomplexBoot.scala

Fixes: https://github.com/paypal/squbs/issues/388
1. The `readConfigs` function which reads from jar file or a directory, defines two functions, based on the type of file passed as input (jar or directory). That can be refactored into two private functions.
2. The current file being processed is modified in both the functions mentioned in the previous point. We could reduce the footprint of that `var` variable by modifying it only before calling the refactored functions.
3. The code actually is written in a little imperative style. We could refactor it with the functional goodies of Scala.

#388 Refactor readConfigs(file)

---

squbs-pattern/src/main/scala/org/squbs/pattern/stream/PersistentQueue.scala
squbs-pattern/src/test/scala/org/squbs/pattern/stream/PersistentQueueSpec.scala

#401 Time window based auto cleanup for Persistent Buffer

---

squbs-actormonitor/src/main/scala/org/squbs/actormonitor/ActorMonitorBean.scala
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/ServiceRegistry.scala
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/ServiceRegistryBase.scala
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/Unicomplex.scala
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/UnicomplexBoot.scala
squbs-zkcluster/src/main/scala/org/squbs/cluster/ZkCluster.scala
squbs-zkcluster/src/main/scala/org/squbs/cluster/ZkPartitionsManager.scala
squbs-zkcluster/src/main/scala/org/squbs/cluster/package.scala

Fixes: https://github.com/paypal/squbs/issues/413

#413: avoid catching Exception and Throwable

---

docs/validation.md

- Updating validation directive example to bring implicit person validator in scope and updating the spray references

#411 Update Validation Directives Documentation

---

docs/marshalling.md

#368 Clarified the use case for the squbs marshalling library.

---

docs/resolver.md

There are certain comments that may need discussion. Please see responses to review comments at the same URL as above (PR378).

#394 - Fixed up documentation as per comments left at #378

---

CONTRIBUTING.md
README.md
docs/actor-hierarchy.md
docs/blocking-dispatcher.md
docs/bootstrap.md
docs/configuration.md
docs/console.md
docs/http-services.md
docs/httpclient.md
docs/lifecycle.md
docs/messages.md
docs/monitor.md
docs/orchestration_dsl.md
docs/persistent-buffer.md
docs/pipeline.md
docs/principles_of_the_squbs_design.md
docs/registry.md
docs/streams-lifecycle.md
docs/testing.md
docs/timeoutpolicy.md
docs/validation.md
docs/zkcluster.md

Placed a space between the hash sign and the header text when not already there.

#427 Updated headers in all docs

---

docs/httpclient.md
squbs-httpclient/src/main/scala/org/squbs/httpclient/ClientFlow.scala
squbs-httpclient/src/main/scala/org/squbs/httpclient/HttpEndpoint.scala
squbs-httpclient/src/test/java/org/squbs/httpclient/ClientFlowHttpsEndpointTest.java
squbs-httpclient/src/test/scala/org/squbs/httpclient/ClientConfigurationSpec.scala
squbs-httpclient/src/test/scala/org/squbs/httpclient/ClientFlowHttpsSpec.scala

#429 `HttpEndpoint` should take an optional `Config`

---

squbs-unicomplex/src/main/scala/org/squbs/unicomplex/UnicomplexBoot.scala

Note: Tested by checking the unicomplex unit test logs for the correct class names.

#416 Fixed shutdown message to show real extension class name

---

squbs-ext/src/test/scala/org/squbs/streams/TimeoutBidiFlowSpec.scala
squbs-ext/src/test/scala/org/squbs/streams/circuitbreaker/CircuitBreakerBidiFlowSpec.scala

#434 Compiler warning for match case block in tests

---

squbs-unicomplex/src/main/scala/org/squbs/unicomplex/FlowHandler.scala

#421 Removed dead code from FlowHandler and refactored/simplified areas.

---

squbs-pipeline/src/main/scala/org/squbs/pipeline/RequestContext.scala
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/FlowHandler.scala

#437 Changed RequestContext id and generator to Long

---

build.sbt

#444 Set all travis build parallelism to 1

---

docs/httpclient.md
squbs-httpclient/src/main/scala/org/squbs/httpclient/ClientFlow.scala
squbs-httpclient/src/test/java/org/squbs/httpclient/ClientFlowCircuitBreakerTest.java
squbs-httpclient/src/test/scala/org/squbs/httpclient/ClientFlowCircuitBreakerSpec.scala
squbs-httpclient/src/test/scala/org/squbs/httpclient/HttpClientJMXSpec.scala

#371 Disable Circuit Breaker by default for Http Client

---

index.html

#348 Update website to have Akka HTTP instead of Spray

---

index.html
stylesheets/stylesheet.css

#466 Add View Docs link for readthedocs

---

project/Versions.scala
project/build.properties
project/plugins.sbt
squbs-ext/src/main/scala/akka/http/org/squbs/util/JavaConverters.scala
squbs-ext/src/main/scala/org/squbs/streams/Deduplicate.scala
squbs-httpclient/build.sbt
squbs-httpclient/src/test/scala/org/squbs/httpclient/TimeBucketMetricsSpec.scala
squbs-httpclient/src/test/scala/org/squbs/httpclient/dummy/DummyService.scala
squbs-pattern/src/main/scala/org/squbs/pattern/orchestration/japi/AbstractOrchestrator.scala
squbs-pattern/src/test/java/org/squbs/pattern/orchestration/japi/AskOrchestrator.java
squbs-pattern/src/test/java/org/squbs/pattern/orchestration/japi/SelectionOrchestrator.java
squbs-pattern/src/test/java/org/squbs/pattern/orchestration/japi/ServiceEmulator.java
squbs-pattern/src/test/java/org/squbs/pattern/orchestration/japi/TestOrchestrator.java
squbs-pipeline/build.sbt
squbs-testkit/src/test/java/org/squbs/testkit/TestActorJ.java
squbs-testkit/src/test/java/org/squbs/testkit/japi/CustomTestKitTest.java
squbs-testkit/src/test/java/org/squbs/testkit/japi/DecrementActor.java
squbs-testkit/src/test/java/org/squbs/testkit/japi/IncrementActor.java
squbs-testkit/src/test/java/org/squbs/testkit/stress/LoadActorTest.java
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/Unicomplex.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/ListenerStateSpec.scala
squbs-zkcluster/src/main/scala/org/squbs/cluster/RemoteGuardian.scala
squbs-zkcluster/src/test/scala/org/squbs/cluster/test/ZkClusterMultiActorSystemTestKit.scala

#459 Upgrade to Akka 2.5

---

version.sbt

Getting the branch ready for 0.9.1

---

samples/bottles/bottlecube/build.sbt
samples/bottles/bottlesvc/build.sbt
samples/bottles/build.sbt
samples/pubsub/build.sbt
samples/pubsub/pubsubsvc/build.sbt
version.sbt

Master branch is for 0.10

---

squbs-ext/src/test/scala/org/squbs/streams/TimeoutBidiFlowSpec.scala
squbs-ext/src/test/scala/org/squbs/streams/circuitbreaker/CircuitBreakerBidiFlowSpec.scala
squbs-httpclient/src/test/scala/org/squbs/httpclient/ClientFlowCircuitBreakerSpec.scala

#478 Improve the reliability of squbs test executions on travis

---

squbs-ext/src/test/scala/org/squbs/streams/TimeoutBidiFlowSpec.scala
squbs-ext/src/test/scala/org/squbs/streams/circuitbreaker/CircuitBreakerBidiFlowSpec.scala
squbs-httpclient/src/test/scala/org/squbs/httpclient/ClientFlowCircuitBreakerSpec.scala

#478 Improve the reliability of squbs test executions on travis (#482)

---

docs/streams-lifecycle.md
squbs-unicomplex/src/main/scala/org/squbs/stream/PerpetualStream.scala
squbs-unicomplex/src/test/resources/classpaths/PerpetualStreamMergeHubSpec/META-INF/squbs-meta.conf
squbs-unicomplex/src/test/scala/org/squbs/stream/PerpetualStreamMergeHubSpec.scala

#462 Perpetual Stream should allow overriding the state to run a stream

---

project/Versions.scala
samples/bottles/bottlecube/build.sbt
samples/bottles/bottlesvc/build.sbt
samples/pubsub/pubsubsvc/build.sbt
squbs-ext/src/main/scala/akka/http/org/squbs/util/JavaConverters.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/ListenerStateSpec.scala

#489 Upgrade to Akka 2.4.18 and Akka HTTP 10.0.9

---

project/Versions.scala
samples/bottles/bottlecube/build.sbt
samples/bottles/bottlesvc/build.sbt
samples/pubsub/pubsubsvc/build.sbt

#489 Upgrade to Akka 2.4.20

---

project/Versions.scala
squbs-actorregistry/build.sbt
squbs-ext/build.sbt
squbs-ext/src/main/scala/org/squbs/streams/Deduplicate.scala
squbs-ext/src/main/scala/org/squbs/streams/UniqueId.scala
squbs-ext/src/main/scala/org/squbs/streams/circuitbreaker/japi/CircuitBreakerSettings.scala
squbs-httpclient/build.sbt
squbs-pattern/build.sbt
squbs-testkit/build.sbt
squbs-testkit/src/main/scala/org/squbs/testkit/stress/LoadActor.scala
squbs-unicomplex/build.sbt

#112 Remove usage of FunctionConverters from Java 8 compat package

---

project/Versions.scala

#505 Upgrade to Akka 2.5.4 and Akka HTTP 10.0.9

---

docs/streams-lifecycle.md

Improving "Connecting a Perpetual Stream with an HTTP Flow" section (fixes #504)

---

project/Versions.scala

#503 Upgrade to Akka HTTP 10.0.10

---

docs/configuration.md
squbs-unicomplex/src/main/resources/reference.conf
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/FlowHandler.scala
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/JMX.scala
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/JavaServiceDefinitions.scala
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/ServiceRegistry.scala
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/Unicomplex.scala
squbs-unicomplex/src/test/resources/classpaths/MaterializerSpec/META-INF/squbs-meta.conf
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/MaterializerSpec.scala

#502 Allow customizing ActorMaterializerSettings for HTTP endpoints

---

squbs-httpclient/src/main/scala/org/squbs/httpclient/ClientFlow.scala
squbs-httpclient/src/test/scala/org/squbs/httpclient/ClientFlowCircuitBreakerSpec.scala

#490 Http Client Circuit Breaker Integration should pass a drainer

---

docs/flow-retry.md
docs/flow-timeout.md
mkdocs.yml
scalastyle-config.xml
squbs-ext/build.sbt
squbs-ext/src/main/scala/org/squbs/streams/RetryBidi.scala
squbs-ext/src/main/scala/org/squbs/streams/TimeoutBidi.scala
squbs-ext/src/main/scala/org/squbs/streams/circuitbreaker/CircuitBreakerBidi.scala
squbs-ext/src/test/java/org/squbs/streams/RetryBidiTest.java
squbs-ext/src/test/scala/org/squbs/streams/RetryBidiSpec.scala
squbs-testkit/src/main/scala/org/squbs/testkit/Timeouts.scala

Retry stage 417

---

project/Versions.scala

#524 Upgrade to akka 10.0.10

---

squbs-ext/src/main/scala/org/squbs/streams/TimeoutBidi.scala

#519: fix high CPU usage with Circuit Breaker combined with ClientFlow

---

docs/lifecycle.md
docs/streams-lifecycle.md
squbs-unicomplex/build.sbt
squbs-unicomplex/src/main/scala/org/squbs/lifecycle/GracefulStopHelper.scala
squbs-unicomplex/src/main/scala/org/squbs/stream/AbstractPerpetualStream.scala
squbs-unicomplex/src/main/scala/org/squbs/stream/PerpetualStream.scala
squbs-unicomplex/src/main/scala/org/squbs/stream/PerpetualStreamBase.scala
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/Unicomplex.scala
squbs-unicomplex/src/test/java/org/squbs/lifecycle/GracefulStopHelperTest.java
squbs-unicomplex/src/test/java/org/squbs/stream/HttpFlowWithMergeHubJ.java
squbs-unicomplex/src/test/java/org/squbs/stream/IllegalStateStreamJ.java
squbs-unicomplex/src/test/java/org/squbs/stream/KillSwitchStreamJ.java
squbs-unicomplex/src/test/java/org/squbs/stream/KillSwitchWithChildActorStreamJ.java
squbs-unicomplex/src/test/java/org/squbs/stream/PerpetualStreamWithMergeHubJ.java
squbs-unicomplex/src/test/java/org/squbs/stream/ProperShutdownStreamJ.java
squbs-unicomplex/src/test/java/org/squbs/stream/ThrowExceptionStreamJ.java
squbs-unicomplex/src/test/java/org/squbs/stream/javasamples/HttpFlowWithMergeHub.java
squbs-unicomplex/src/test/java/org/squbs/stream/javasamples/MsgReceivingStream.java
squbs-unicomplex/src/test/java/org/squbs/stream/javasamples/PerpetualStreamWithMergeHub.java
squbs-unicomplex/src/test/resources/classpaths/JavaIllegalStateStream/META-INF/squbs-meta.conf
squbs-unicomplex/src/test/resources/classpaths/JavaKillSwitchStream/META-INF/squbs-meta.conf
squbs-unicomplex/src/test/resources/classpaths/JavaKillSwitchWithChildActorStream/META-INF/squbs-meta.conf
squbs-unicomplex/src/test/resources/classpaths/JavaPerpetualStreamMergeHubSpec/META-INF/squbs-meta.conf
squbs-unicomplex/src/test/resources/classpaths/JavaProperShutdownStream/META-INF/squbs-meta.conf
squbs-unicomplex/src/test/resources/classpaths/JavaThrowExceptionStream/META-INF/squbs-meta.conf
squbs-unicomplex/src/test/scala/org/squbs/lifecycle/GracefulStopHelperSpec.scala
squbs-unicomplex/src/test/scala/org/squbs/stream/JavaPerpetualStreamSpec.scala
squbs-unicomplex/src/test/scala/org/squbs/stream/PerpetualStreamMergeHubJSpec.scala
squbs-unicomplex/src/test/scala/org/squbs/stream/PerpetualStreamMergeHubSpec.scala
squbs-unicomplex/src/test/scala/org/squbs/stream/ThrowExceptionStream.scala

And beefed up Java support around the API usage.

#538: Added PerpetualStream Java API 

---

squbs-unicomplex/src/main/scala/org/squbs/unicomplex/ServiceRegistry.scala

#533 Obscure error "Failed to build streaming flow handler"

---

squbs-admin/src/main/scala/org/squbs/admin/AdminSvc.scala
squbs-admin/src/test/scala/org/squbs/admin/AdminSvcTest.scala

#535 Incorrect links in admin tool

---

.travis.yml
build.sbt
squbs-ext/src/test/scala/org/squbs/streams/DemandSupplyMetricsSpec.scala
squbs-pattern/src/test/scala/org/squbs/pattern/orchestration/OrchestratorSpec.scala
squbs-pattern/src/test/scala/org/squbs/pattern/stream/PersistentBufferAtLeastOnceSpec.scala
squbs-pattern/src/test/scala/org/squbs/pattern/stream/PersistentBufferSpec.scala
squbs-unicomplex/src/main/scala/org/squbs/stream/PerpetualStreamBase.scala

 #540: Fix intermittent test failure in Travis

---

squbs-actorregistry/src/main/scala/org/squbs/actorregistry/ActorRegistry.scala
squbs-actorregistry/src/test/resources/classpaths/NoWellKnownActorsCube/META-INF/squbs-meta.conf
squbs-actorregistry/src/test/scala/org/squbs/actorregistry/NoWellKnownActorsSpec.scala

#536 ActorRegistry should initialize even without any well known actors

---

squbs-pattern/src/test/scala/org/squbs/pattern/stream/PersistentBufferSpec.scala

 #540: one more test fix

---

build.sbt
project/build.properties
project/plugins.sbt
squbs-pattern/build.sbt

Fix #497.
Although the original issue indicated `1.0.0`, I still migrated to `1.0.4`. Since sbt `1.0.0` to `1.0.4`, there were some issues had been solving which included some of performance regressions.

Update to sbt 1.0.4. (#497)

---

squbs-unicomplex/src/test/scala/org/squbs/unicomplex/MultiListenerSpec.scala

#520 Expose a codahale Metric for new connections rate - fix broken test

---

squbs-pattern/src/test/scala/org/squbs/pattern/stream/BroadcastBufferSpec.scala

#569: Fix intermittent travis test failure

---

squbs-unicomplex/src/test/scala/org/squbs/unicomplex/ConnectionMetricsSpec.scala

#520 Expose a codahale Metric for new connections rate - test stability

---

docs/persistent-buffer.md
project/Versions.scala
squbs-pattern/build.sbt

Update the chronicle-queue version to 4.5.2
This may also fix an intermitten test failure.

 #554 Update chronicle-queue version

---

squbs-testkit/src/main/scala/org/squbs/testkit/TestRoute.scala
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/ServiceRegistry.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/RouteDefinitionSpec.scala

Ensure default exception handler is used (fixes #560)

---

squbs-httpclient/src/main/scala/org/squbs/httpclient/ClientFlow.scala
squbs-httpclient/src/main/scala/org/squbs/httpclient/DefaultHttpEndpointResolver.scala
squbs-httpclient/src/main/scala/org/squbs/httpclient/HttpEndpoint.scala
squbs-httpclient/src/test/java/org/squbs/httpclient/HttpClientTest.java
squbs-httpclient/src/test/java/org/squbs/httpclient/JavaEndpointResolver2.java
squbs-httpclient/src/test/scala/org/squbs/httpclient/DefaultHttpEndpointResolverSpec.scala

Replaced `java.net.URI` with `akka.http.scaladsl.model.Uri` (Fixes #449)

---

project/Versions.scala

#596 Upgrade jackson version

---

docs/circuitbreaker.md
docs/flow-retry.md
docs/flow-timeout.md
squbs-ext/src/main/scala/org/squbs/streams/RetryBidi.scala
squbs-ext/src/main/scala/org/squbs/streams/TimeoutBidi.scala
squbs-ext/src/main/scala/org/squbs/streams/UniqueId.scala
squbs-ext/src/main/scala/org/squbs/streams/circuitbreaker/CircuitBreakerBidi.scala
squbs-ext/src/main/scala/org/squbs/streams/circuitbreaker/japi/CircuitBreakerSettings.scala
squbs-ext/src/test/java/org/squbs/streams/RetryBidiTest.java
squbs-ext/src/test/java/org/squbs/streams/TimeoutBidiFlowTest.java
squbs-ext/src/test/java/org/squbs/streams/circuitbreaker/CircuitBreakerBidiFlowTest.java
squbs-ext/src/test/scala/org/squbs/streams/RetryBidiSpec.scala
squbs-ext/src/test/scala/org/squbs/streams/TimeoutBidiFlowSpec.scala
squbs-ext/src/test/scala/org/squbs/streams/circuitbreaker/CircuitBreakerBidiFlowSpec.scala
squbs-httpclient/src/main/scala/org/squbs/httpclient/ClientFlow.scala

#576 Unique Id Mapper should not return an option

---

docs/httpclient.md
squbs-ext/src/main/scala/org/squbs/metrics/MetricsFlow.scala
squbs-httpclient/src/test/scala/org/squbs/httpclient/MetricsFlowSpec.scala
squbs-unicomplex/src/test/resources/classpaths/pipeline/MetricsFlowSpec/META-INF/squbs-meta.conf
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/pipeline/MetricsFlowSpec.scala

#556: Add a response metric to MetricsFlow

---

.travis.yml

#602 Changing the publish task

---

squbs-unicomplex/src/test/scala/org/squbs/unicomplex/ConnectionMetricsSpec.scala

#602 Sparodic test failures connection metrics

---

build.sbt

#602 sbt publish snapshot overwrite

---

.travis.yml
build.sbt

#602 sbt publish snapshot overwrite - temporarily publish without sign

---

README.md
docs/index.md

Change wording on documentation to prevent confusion

---

docs/circuitbreaker.md
docs/flow-retry.md
docs/flow-timeout.md
squbs-ext/src/main/scala/org/squbs/streams/Retry.scala
squbs-ext/src/main/scala/org/squbs/streams/Timeout.scala
squbs-ext/src/main/scala/org/squbs/streams/circuitbreaker/CircuitBreaker.scala
squbs-ext/src/main/scala/org/squbs/streams/circuitbreaker/japi/CircuitBreakerSettings.scala
squbs-ext/src/test/java/org/squbs/streams/BoundedOrderingTest.java
squbs-ext/src/test/java/org/squbs/streams/RetryTest.java
squbs-ext/src/test/java/org/squbs/streams/TimeoutTest.java
squbs-ext/src/test/java/org/squbs/streams/circuitbreaker/CircuitBreakerStateTest.java
squbs-ext/src/test/java/org/squbs/streams/circuitbreaker/CircuitBreakerTest.java
squbs-ext/src/test/scala/org/squbs/streams/RetrySpec.scala
squbs-ext/src/test/scala/org/squbs/streams/TimeoutSpec.scala
squbs-ext/src/test/scala/org/squbs/streams/circuitbreaker/CircuitBreakerSpec.scala
squbs-httpclient/src/main/scala/org/squbs/httpclient/ClientFlow.scala

#601 Drop Bidi from stage name and add settings for Timeout

---

.travis.yml
build.sbt
project/plugins.sbt

sbt-pgp#121 Upgrade to 1.1.1

---

project/Versions.scala
squbs-ext/src/main/scala/akka/http/org/squbs/util/JavaConverters.scala
squbs-httpclient/src/main/scala/org/squbs/httpclient/HttpEndpoint.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/MaterializerSpec.scala

#572 Akka HTTP 10.1.0 & Akka 2.5.11

---

squbs-httpclient/src/main/scala/org/squbs/httpclient/ClientFlow.scala
squbs-httpclient/src/main/scala/org/squbs/httpclient/HttpClientJMX.scala
squbs-httpclient/src/test/scala/org/squbs/httpclient/ClientFlowSpec.scala
squbs-httpclient/src/test/scala/org/squbs/httpclient/HttpClientJMXSpec.scala

#616 Use effective port in ClientFlow

---

squbs-actormonitor/src/main/scala/org/squbs/actormonitor/ActorMonitor.scala
squbs-actorregistry/src/main/scala/org/squbs/actorregistry/ActorRegistry.scala
squbs-admin/src/main/scala/org/squbs/admin/MBeanUtil.scala
squbs-admin/src/test/scala/org/squbs/admin/MBeanUtilTest.scala
squbs-ext/src/main/scala/org/squbs/env/Environment.scala
squbs-ext/src/main/scala/org/squbs/resolver/Resolver.scala
squbs-ext/src/main/scala/org/squbs/util/ConfigUtil.scala
squbs-ext/src/test/scala/org/squbs/marshallers/json/TestData.scala
squbs-pattern/src/test/scala/org/squbs/pattern/stream/StreamSpecUtil.scala
squbs-pipeline/src/main/scala/org/squbs/pipeline/PipelineExtension.scala
squbs-testkit/src/main/scala/org/squbs/testkit/CustomTestKit.scala
squbs-testkit/src/main/scala/org/squbs/testkit/japi/CustomTestKit.scala
squbs-testkit/src/main/scala/org/squbs/testkit/japi/JUnitCustomRouteTestKit.scala
squbs-testkit/src/main/scala/org/squbs/testkit/japi/TestNGCustomRouteTestKit.scala
squbs-testkit/src/test/java/org/squbs/testkit/japi/CustomTestKitTest.java
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/JMX.scala
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/ServiceRegistry.scala
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/ServiceRegistryBase.scala
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/Unicomplex.scala
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/UnicomplexBoot.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/SystemSettingBeanSpec.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/SystemStatusTest.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/UnicomplexBootSpec.scala
squbs-zkcluster/src/main/scala/org/squbs/cluster/ZkCluster.scala
squbs-zkcluster/src/main/scala/org/squbs/cluster/ZkClusterActor.scala
squbs-zkcluster/src/main/scala/org/squbs/cluster/ZkMembershipMonitor.scala
squbs-zkcluster/src/main/scala/org/squbs/cluster/ZkPartitionsManager.scala
squbs-zkcluster/src/main/scala/org/squbs/cluster/package.scala

#618 remove deprecated JavaConversions and use JavaConverters instead

---

docs/flow-retry.md
squbs-ext/src/main/scala/org/squbs/streams/Retry.scala
squbs-ext/src/test/scala/org/squbs/streams/RetrySpec.scala

#623 Retry should be able to resume after a backpressure

---

build.sbt

 #627: Update to scala version 2.12.5

---

squbs-admin/build.sbt

#596 json4s brings older version of jackson

---

version.sbt

Release version 0.10.0

---

README.md

#632 Updated badge link for maven badge

---

index.html

#632 Update badge link for maven on gh-pages (#633)

---

README.md

 #632 Updated badge link for license badge

---

docs/configuration.md
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/Unicomplex.scala
squbs-unicomplex/src/test/java/org/squbs/unicomplex/MaterializerTest.java
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/MaterializerSpec.scala

Added Java API, test, and documentation updates to reflect this API.

Added Java API for accessing the system materializer. (fixes #637)

---

docs/bootstrap.md
docs/configuration.md
docs/http-services.md
docs/httpclient.md
docs/marshalling.md
docs/orchestration_dsl.md
docs/zkcluster.md

Just some super trivial grammar stuff.  However, there are a few changes to code snippets.

 #651 Minor doc updates

---

squbs-actormonitor/src/test/scala/org/squbs/actormonitor/ActorMonitorSpec.scala
squbs-ext/src/test/java/org/squbs/streams/RetryTest.java
squbs-unicomplex/src/test/scala/org/squbs/dispatcher/ForkJoinConfiguratorSpec.scala
squbs-unicomplex/src/test/scala/org/squbs/stream/TriggerMergeJSpec.scala
squbs-unicomplex/src/test/scala/org/squbs/stream/TriggerMergeSpec.scala
squbs-unicomplex/src/test/scala/org/squbs/stream/UnicomplexActorPublisherJSpec.scala
squbs-unicomplex/src/test/scala/org/squbs/stream/UnicomplexActorPublisherSpec.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/BadUnicomplexBootSpec.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/ScanResourceSpec.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/StopAndStartCubeSpec.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/StreamTestSpec.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/UnicomplexSpec.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/UnicomplexTimeoutSpec.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/dummysvcactor/DummySvcActor.scala
squbs-unicomplex/src/test/scala/org/squbs/unicomplex/pipeline/PipelineChunkingSpec.scala
squbs-zkcluster/src/test/scala/org/squbs/cluster/DataCenterAwarenessSpec.scala

Replace deprecated methods and classes. I will squash after reviewing.

Replace deprecated methods and classes

---

docs/presentations.md

#656 Add link to QCon London presentation

---

.travis.yml
build.sbt
project/Versions.scala
project/build.properties
squbs-httpclient/src/main/scala/org/squbs/httpclient/HttpEndpoint.scala
squbs-zkcluster/build.sbt

#635 Use new API from Akka-HTTP 10.1.1

---

docs/customizing-stream-control.md
squbs-unicomplex/src/main/scala/org/squbs/stream/UnicomplexActorPublisher.scala
squbs-unicomplex/src/test/java/org/squbs/stream/ProperShutdownStreamJ.java
squbs-unicomplex/src/test/java/org/squbs/stream/UnicomplexActorPublisherJ.java
squbs-unicomplex/src/test/scala/org/squbs/stream/ProperShutdownStream.scala
squbs-unicomplex/src/test/scala/org/squbs/stream/UnicomplexActorPublisherSpec.scala

Re-add the actorsystem as implicit in unicomplex LifecycleManaged

 #638: LifecycleManaged should not rely on system

---

squbs-pipeline/src/main/scala/org/squbs/pipeline/RequestContext.scala
squbs-pipeline/src/test/java/org/squbs/pipeline/RequestContextTest.java
squbs-pipeline/src/test/scala/org/squbs/pipeline/RequestContextSpec.scala

 #613 Add withAttributes/removeAttributes methods

---

squbs-unicomplex/src/main/scala/org/squbs/stream/PerpetualStreamBase.scala

Made `MatValueRequest` accessible from Java (fixes #663)

---

docs/circuitbreaker.md

Noticed this typo as I was reading the documentation.  Keep up the good work!

#671 - Fix typo - intered => interested

---

squbs-httpclient/build.sbt
squbs-httpclient/src/main/scala/org/squbs/httpclient/ClientFlow.scala
squbs-httpclient/src/test/scala/org/squbs/httpclient/ClientFlowHttpsProxySpec.scala
squbs-httpclient/src/test/scala/org/squbs/httpclient/ClientFlowHttpsSpec.scala
squbs-httpclient/src/test/scala/org/squbs/httpclient/package.scala

Added proxy configuration and proxy tests (fixes #636)

---

version.sbt

 #673: Update squbs version

---

version.sbt

Release version 0.11.0

---

squbs-unicomplex/src/main/scala/org/squbs/unicomplex/Unicomplex.scala
squbs-unicomplex/src/main/scala/org/squbs/unicomplex/UnicomplexBoot.scala

 #683 Log an error when service startup fails.

---

docs/testing.md

When read from readthedocs we need a full link to link to code.

Updated broken link (fixes #675)

---

squbs-unicomplex/src/main/scala/org/squbs/unicomplex/Unicomplex.scala

- [x ] Title includes issue id.
- [x ] Description of the change added.

683 Adhere to file's convention (`sender()` not `sender`).

---

squbs-pattern/build.sbt
squbs-pattern/src/main/scala/org/squbs/pattern/stream/PersistentQueue.scala
squbs-pattern/src/test/scala/org/squbs/pattern/stream/BroadcastBufferAtLeastOnceSpec.scala
squbs-pattern/src/test/scala/org/squbs/pattern/stream/BroadcastBufferCommitOrderSpec.scala
squbs-pattern/src/test/scala/org/squbs/pattern/stream/BroadcastBufferSpec.scala
squbs-pattern/src/test/scala/org/squbs/pattern/stream/PersistentBufferAtLeastOnceSpec.scala
squbs-pattern/src/test/scala/org/squbs/pattern/stream/PersistentBufferCommitOrderSpec.scala
squbs-pattern/src/test/scala/org/squbs/pattern/stream/PersistentBufferSpec.scala
squbs-pattern/src/test/scala/org/squbs/pattern/stream/StreamSpecUtil.scala

Still a temporary pull request to understand issues with Chronicle Queue.

Fixing BroadcastBuffer build failures (#569)

---

squbs-unicomplex/src/test/scala/org/squbs/stream/PerpetualStreamMatValueSpec.scala

It's a bit of a hack, but likely justified.

 #569 Poll a bit for actor system state to stabilize

---

.travis.yml
project/Versions.scala
project/build.properties
project/plugins.sbt
squbs-ext/src/test/java/org/squbs/streams/circuitbreaker/CircuitBreakerStateTest.java
squbs-testkit/src/test/java/org/squbs/testkit/japi/IncrementActor.java

Update akka dependency, sbt version and other sbt plugins

---

project/build.properties

#695: Bump sbt version to 1.2.8

---

docs/registry.md
squbs-actorregistry/src/main/scala/org/squbs/actorregistry/japi/ActorLookup.scala
squbs-actorregistry/src/test/java/org/squbs/actorregistry/japi/ActorRegistryTest.java

Ensure all ActorRegistry Java API uses CompletableFuture (#704)

---

.travis.yml
build.sbt
compileOptions.sbt
project/Versions.scala
squbs-ext/src/main/scala/org/squbs/streams/BoundedOrdering.scala
squbs-ext/src/main/scala/org/squbs/streams/Deduplicate.scala
squbs-ext/src/main/scala/org/squbs/streams/Timeout.scala
squbs-ext/src/test/java/org/squbs/streams/RetryTest.java
squbs-ext/src/test/java/org/squbs/streams/TimeoutTest.java
squbs-ext/src/test/scala/org/squbs/streams/TimeoutSpec.scala
squbs-httpclient/src/main/scala/org/squbs/httpclient/ClientFlow.scala
squbs-pattern/src/main/scala/org/squbs/pattern/stream/PersistentQueue.scala
squbs-pipeline/src/main/scala/org/squbs/pipeline/PipelineExtension.scala
squbs-pipeline/src/test/java/org/squbs/pipeline/DummyFlow2J.java
squbs-pipeline/src/test/java/org/squbs/pipeline/DummyFlowJ.java
squbs-pipeline/src/test/java/org/squbs/pipeline/PostFlowJ.java
squbs-pipeline/src/test/java/org/squbs/pipeline/PreFlowJ.java
squbs-testkit/src/main/scala/org/squbs/testkit/CustomTestKit.scala
squbs-testkit/src/test/java/org/squbs/testkit/japi/CustomTestKitTest.java
squbs-unicomplex/src/main/scala/org/squbs/dispatcher/ForkJoinConfigurator.scala
squbs-unicomplex/src/main/scala/org/squbs/lifecycle/GracefulStopHelper.scala
squbs-unicomplex/src/main/scala/org/squbs/stream/AbstractPerpetualStream.scala
squbs-zkcluster/src/main/scala/org/squbs/cluster/ZkCluster.scala
squbs-zkcluster/src/main/scala/org/squbs/cluster/ZkPartitionsManager.scala

Added changes for code to support scala 2.11 and scala 2.12

#707 Added support for scala 2.11 

---

squbs-ext/src/main/scala/org/squbs/streams/Timeout.scala
squbs-ext/src/main/scala/org/squbs/streams/circuitbreaker/impl/AtomicCircuitBreakerState.scala
squbs-ext/src/main/scala/org/squbs/util/DurationConverters.scala
squbs-ext/src/test/java/org/squbs/streams/circuitbreaker/CircuitBreakerStateTest.java
squbs-httpclient/src/test/java/org/squbs/httpclient/ClientFlowTest.java
squbs-pattern/src/main/scala/org/squbs/pattern/timeoutpolicy/TimeoutPolicy.scala
squbs-pattern/src/test/java/org/squbs/pattern/timeoutpolicy/TimeoutPolicyJ.java
squbs-unicomplex/src/main/scala/org/squbs/lifecycle/GracefulStopHelper.scala
squbs-unicomplex/src/test/java/org/squbs/stream/ProperShutdownStreamJ.java

Standardized duration conversion and always make it coarsest possible (fixes #715)

---

version.sbt

Release 0.12.0

---

version.sbt

Rev next version to 0.13.0-SNAPSHOT

---

docs/configuration.md
squbs-unicomplex/src/main/resources/reference.conf

- [x ] Title includes issue id.
- [ x] Description of the change added.
- [ x] Commits are squashed.
- [ x] Documentation added/updated.

 #711 Document service infra timeouts.

---

version.sbt

 #731: Release milestone 0.13.0

---

build.sbt
project/plugins.sbt
version.sbt

 #731: Fix RELEASE publishing by reverting sbt pgp plugin version

---

version.sbt

Rev version to the next release iteration

---

.gitignore
project/Versions.scala
squbs-actormonitor/build.sbt
squbs-actorregistry/build.sbt
squbs-admin/build.sbt
squbs-httpclient/build.sbt
squbs-pipeline/build.sbt
squbs-unicomplex/build.sbt
squbs-zkcluster/build.sbt
version.sbt

Prepare for release 0.14.0

---

.github/workflows/pull-request.yml

#746: First trial with github actions

---

version.sbt

Release squbs 0.15.0

---

publish.sbt

Release squbs 0.15.0 - update pom config

---

version.sbt

Rev to the next iteration 0.15.1-SNAPSHOT
